services:
  app:
    build: .
    image: mytoolboxapp:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
