services:
  app:
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mytoolboxapp.rule=Host(`mytoolboxapp.lan.logiko.net`)"
      - "traefik.http.routers.mytoolboxapp.entrypoints=websecure"
      - "traefik.http.routers.mytoolboxapp.tls=true"
      - "traefik.http.services.mytoolboxapp.loadbalancer.server.port=3000"
    ports: []

networks:
  proxy:
    external: true
